### ISSUE TITLE
Would love to share our related work!

### ISSUE THREAD

**Issue by linzhiqiu** [tripletclip/TripletCLIP#1]
Interesting work! I would love to share our recent work on compositional reasoning using generative vision-language models:

1 - [VisualGPTScore](https://linzhiqiu.github.io/papers/visual_gpt_score/) (ICML'24): We find that P(caption | image) is a strong image-text matching score with strong compositional reasoning capabilities.
2 - [VQAScore](https://linzhiqiu.github.io/papers/vqascore/) (ECCV'24): We improve VisualGPTScore by prompting it into a simple yes-or-no question. This results in VQAScore, a simple but effective image-text similarity score that can be run using one-line Python code [here](https://github.com/linzhiqiu/t2v_metrics)! It also significantly outperforms previous automated metrics such as ImageReward, HPSv2, and PickScore. Google's [Imagen3](https://arxiv.org/abs/2408.07009) reported VQAScore as the strongest replacement for CLIPScore.
Best,
Zhiqiu

**Comment by Maitreyapatel** [comment]
Thanks for sharing!
